export const documentType = [
  {
    label: "Employee Photo",
    input: "EMPLOYEE_PHOTO",
    desc: "* Employee Photo format must be in jpeg/png/jpg",
    fileSize: "* File size should be max 5MB",
    id: 1,
  },
  {
    label: "Curriculum Vitae",
    input: "CURRICULUM_VITAE",
    desc: "* Curriculum vitue format must be in jpeg/png/jpg",
    fileSize: "* File size should be max 5MB",
    id: 2,
  },
  {
    label: "Citizenship",
    input: "CITIZENSHIP",
    desc: "* Citizenship photo format must be in jpeg/png/jpg",
    fileSize: "* File size should be max 5MB",
    id: 3,
  },
  {
    label: "PAN Card",
    input: "PAN_CARD",
    desc: "* Pan card image format must be in jpeg/png/jpg",
    fileSize: "* File size should be max 5MB",
    id: 4,
  },
  {
    label: "Academic Document",
    input: "ACADEMIC_DOCUMENT",
    desc: "* Academic document format must be in pdf",
    fileSize: "* File size should be max 25MB",
    id: 5,
  },
  {
    label: "Training Certificate",
    input: "TRAINING_CERTIFICATE",
    desc: "* Training certificate format must be in pdf",
    fileSize: "* File size should be max 25MB",
    id: 6,
  },
  {
    label: "Certification",
    input: "CERTIFICATION",
    desc: "* Certication document must be in pdf format",
    fileSize: "* File size should be max 25MB",
    id: 7,
  },
  {
    label: "Experience Letter",
    input: "EXPERIENCE_LETTER",
    desc: "* Experience letter must be in pdf",
    fileSize: "* File size should be max 25MB",
    id: 8,
  },
  {
    label: "Award and Achievement",
    input: "AWARD_AND_ACHIEVEMENT",
    desc: "* Image Format must be in pdf",
    fileSize: "* File size should be max 25MB",
    id: 9,
  },
  {
    label: "Signed Contract",
    input: "SIGNED_CONTRACT",
    desc: "* Image Format must be in jpeg/jpg/png",
    fileSize: "* File size should be max 25MB",
    id: 10,
  },
  {
    label: "Health Insurance",
    input: "HEALTH_INSURANCE",
    desc: "* Image Format must be in jpeg",
    fileSize: "* File size should be max 25MB",
    id: 11,
  },
  {
    label: "Other Document",
    input: "OTHER_DOCUMENT ",
    desc: "* Image Format must be in pdf",
    fileSize: "* File size should be max 25MB",
    id: 12,
  },
];
